language: node_js
node_js:
  - "4.3"
  - "5.6"
before_install:
  - npm install -g typescript typings nodemon coveralls
install:
  - npm install
script:
  - npm test
after_success:
  - coveralls < coverage/lcov.info